version: '3.8'

services:
  app:
    build: .
    container_name: promtior_fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
